SHOW DATABASES
SHOW SCHEMAS
USE test_database
USE SCHEMA test_schema

CREATE TABLE TEST_TABLE (
	TEST_NUMBER NUMBER,
	TEST_VARCHAR VARCHAR,
	TEST_BOOLEAN BOOLEAN,
	TEST_DATE DATE,
	TEST_VARIANT VARIANT,
	TEST_GEOGRAPHY GEOGRAPHY
);

INSERT INTO TEST_DATABASE.TEST_SCHEMA.TEST_TABLE
  VALUES
  (28, 'ha!', True, '2024-01-01', NULL, NULL);

  SHOW TABLES

  CREATE TABLE test_table2 (
  TEST_NUMBER NUMBER
  )

  INSERT INTO test_table2 
  values
  (42)

  SHOW TABLES

  DROP TABLE test_table
  UNDROP TABLE test_table