CREATE WAREHOUSE IF NOT EXISTS warehouse_one;

SHOW WAREHOUSES

CREATE WAREHOUSE IF NOT EXISTS warehouse_two;

USE WAREHOUSE warehouse_two

SHOW WAREHOUSES

DROP WAREHOUSE warehouse_two

USE WAREHOUSE warehouse_one

ALTER WAREHOUSE SET warehouse_size="SMALL"

SHOW WAREHOUSES

ALTER WAREHOUSE SET auto_suspend=120

SHOW WAREHOUSES
