SELECT * FROM TASTY_BYTES_SAMPLE_DATA.RAW_POS.MENU;

SELECT COUNT(*)
FROM TASTY_BYTES_SAMPLE_DATA.RAW_POS.MENU
WHERE ITEM_CATEGORY='Snack' and item_subcategory='Warm Option'

SELECT MAX(SALE_PRICE_USD) AS MAX
FROM TASTY_BYTES_SAMPLE_DATA.RAW_POS.MENU
GROUP BY ITEM_SUBCATEGORY
ORDER BY MAX DESC;