version: '3.1'
services:
  postgres_dw:
    image: postgres:15
    environment:
      - POSTGRES_USER="bunyod"
      - POSTGRES_PASSWORD="12345678"
      - POSTGRES_DB="analytics"
    ports:
      - "5432:5432"