global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi_investments'
    static_configs:
      # host.docker.internal allows the Docker container to talk to your local machine
      - targets: ['host.docker.internal:8000']